#!/usr/bin/env bash
# cookbook filename: interactive

case "$-" in
    *i*) # Code for interactive shell here
	echo "list of params: $- "
         ;;
    *)   # Code for non-interactive shell here
	echo "list of params: $- "
         ;;
esac
